Optimization: prevent empty COMMIT calls
rails/activerecord-session_store pull request #166
Opened 2020-10-24 16:06 UTC by chaffeqa

Prevents `BEGIN COMMIT` empty database calls after each rails request if the session did not change.

Don't know why the `write_session` is called in our app every request, but monkey patching using this logic prevents an empty write at the end of each request.

2021-03-10 05:01 UTC, sikachu requested changes
Thank you for the PR. Please see my inline comment below.

2021-05-03 16:09 UTC, chaffeqa commented on lib/action_dispatch/session/active_record_store.rb
> +          return false if record.changed? and not record.save
done! sorry for looooong delay

2022-10-17 15:14 UTC, h0jeZvgoxFepBQ2C commented
Can this be merged?

2023-08-23 14:00 UTC, preethi29 commented
any update on this? this seems to be useful.

Also the store seems to record empty session on every request without valid session. Is there a way to optimise it other than overriding `save`?

2026-07-13 18:40 UTC, merged